[2022-02-11 11:20:07,091] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function scheduled__2022-02-09T00:00:00+00:00 [queued]>
[2022-02-11 11:20:07,133] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function scheduled__2022-02-09T00:00:00+00:00 [queued]>
[2022-02-11 11:20:07,141] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-11 11:20:07,143] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-11 11:20:07,144] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-11 11:20:07,203] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): test_function> on 2022-02-09 00:00:00+00:00
[2022-02-11 11:20:07,217] {standard_task_runner.py:52} INFO - Started process 64 to run task
[2022-02-11 11:20:07,226] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_workflow', 'test_function', 'scheduled__2022-02-09T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/test_workflow.py', '--cfg-path', '/tmp/tmpumtdea3k', '--error-file', '/tmp/tmpxkunztt5']
[2022-02-11 11:20:07,228] {standard_task_runner.py:77} INFO - Job 44: Subtask test_function
[2022-02-11 11:20:07,382] {logging_mixin.py:109} INFO - Running <TaskInstance: test_workflow.test_function scheduled__2022-02-09T00:00:00+00:00 [running]> on host 692d64867305
[2022-02-11 11:20:07,577] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_workflow
AIRFLOW_CTX_TASK_ID=test_function
AIRFLOW_CTX_EXECUTION_DATE=2022-02-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-09T00:00:00+00:00
[2022-02-11 11:20:07,594] {python.py:175} INFO - Done. Returned value was: None
[2022-02-11 11:20:07,644] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=test_workflow, task_id=test_function, execution_date=20220209T000000, start_date=20220211T112007, end_date=20220211T112007
[2022-02-11 11:20:07,790] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-11 11:20:07,899] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
