[2022-02-11 13:08:42,086] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function manual__2022-02-11T13:08:40.340955+00:00 [queued]>
[2022-02-11 13:08:42,099] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function manual__2022-02-11T13:08:40.340955+00:00 [queued]>
[2022-02-11 13:08:42,100] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-11 13:08:42,101] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-11 13:08:42,102] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-11 13:08:42,116] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): test_function> on 2022-02-11 13:08:40.340955+00:00
[2022-02-11 13:08:42,121] {standard_task_runner.py:52} INFO - Started process 169 to run task
[2022-02-11 13:08:42,126] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_workflow', 'test_function', 'manual__2022-02-11T13:08:40.340955+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/test_workflow.py', '--cfg-path', '/tmp/tmpjhb9rq8b', '--error-file', '/tmp/tmp85nhisr6']
[2022-02-11 13:08:42,127] {standard_task_runner.py:77} INFO - Job 56: Subtask test_function
[2022-02-11 13:08:42,193] {logging_mixin.py:109} INFO - Running <TaskInstance: test_workflow.test_function manual__2022-02-11T13:08:40.340955+00:00 [running]> on host 901bf161631a
[2022-02-11 13:08:42,260] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=roni.das39@yahoo.in
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_workflow
AIRFLOW_CTX_TASK_ID=test_function
AIRFLOW_CTX_EXECUTION_DATE=2022-02-11T13:08:40.340955+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-11T13:08:40.340955+00:00
[2022-02-11 13:08:42,267] {python.py:175} INFO - Done. Returned value was: None
[2022-02-11 13:08:42,283] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=test_workflow, task_id=test_function, execution_date=20220211T130840, start_date=20220211T130842, end_date=20220211T130842
[2022-02-11 13:08:42,340] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-11 13:08:42,384] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
