[2022-02-07 17:37:14,111] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function manual__2022-02-07T17:37:11.374295+00:00 [queued]>
[2022-02-07 17:37:14,140] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function manual__2022-02-07T17:37:11.374295+00:00 [queued]>
[2022-02-07 17:37:14,143] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 17:37:14,145] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-07 17:37:14,147] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-07 17:37:14,201] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): test_function> on 2022-02-07 17:37:11.374295+00:00
[2022-02-07 17:37:14,207] {standard_task_runner.py:52} INFO - Started process 660 to run task
[2022-02-07 17:37:14,213] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_workflow', 'test_function', 'manual__2022-02-07T17:37:11.374295+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/test_workflow.py', '--cfg-path', '/tmp/tmp1xxesp_u', '--error-file', '/tmp/tmp3057y_2j']
[2022-02-07 17:37:14,217] {standard_task_runner.py:77} INFO - Job 3: Subtask test_function
[2022-02-07 17:37:14,338] {logging_mixin.py:109} INFO - Running <TaskInstance: test_workflow.test_function manual__2022-02-07T17:37:11.374295+00:00 [running]> on host ddb0c8f14c03
[2022-02-07 17:37:14,649] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_workflow
AIRFLOW_CTX_TASK_ID=test_function
AIRFLOW_CTX_EXECUTION_DATE=2022-02-07T17:37:11.374295+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-07T17:37:11.374295+00:00
[2022-02-07 17:37:14,662] {python.py:175} INFO - Done. Returned value was: None
[2022-02-07 17:37:14,755] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=test_workflow, task_id=test_function, execution_date=20220207T173711, start_date=20220207T173714, end_date=20220207T173714
[2022-02-07 17:37:14,854] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-07 17:37:15,008] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
